Repository sparcs-kaist/otlplus-app, pull requests merged in 2022-10, with the labels that each got.

#69 Fix timetableindex changing to wrong index
  README.md
  android/gradle.properties
  lib/providers/timetable_model.dart
Labels: bug, size/xs

#70 Add review block expandable function
  lib/pages/lecture_detail_page.dart
  lib/widgets/expandable_text.dart
  lib/widgets/review_block.dart
  lib/widgets/review_write_block.dart
  test/widgets/review_block_test.dart
Labels: enhancement, size/m

#72 Update flutter version to 3.3.6 and fix iOS test
  .github/workflows/build.yml
  .github/workflows/coverage.yml
  .github/workflows/deploy.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  README.md
  ios/Flutter/AppFrameworkInfo.plist
  ios/Podfile.lock
  pubspec.lock
Labels: cicd, size/s
