Repository sparcs-kaist/otlplus-app, pull requests merged in 2022-03, with the labels that each got.

#48 Resolve #45, Fix #46, #47
  .github/workflows/build.yml
  .github/workflows/coverage.yml
  .github/workflows/deploy.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
  ios/Podfile.lock
  lib/models/course.dart
  lib/models/lecture.dart
  lib/models/nested_course.dart
  lib/models/nested_lecture.dart
  lib/models/professor.dart
  lib/pages/course_detail_page.dart
  lib/pages/lecture_detail_page.dart
  lib/pages/settings_page.dart
  lib/providers/course_detail_model.dart
  lib/providers/lecture_detail_model.dart
  lib/providers/search_model.dart
  lib/widgets/course_search.dart
  lib/widgets/lecture_search.dart
  pubspec.lock
  pubspec.yaml
  test/utils/samples.dart
Labels: bug, enhancement, size/m

#49 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, size/m

#51 Remove social login from iOS, update firebase
  README.md
  android/app/build.gradle
  android/app/google-services.json
  android/build.gradle
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/GoogleService-Info.plist
  ios/Runner/Info.plist
  lib/firebase_options.dart
  lib/main.dart
  lib/pages/login_page.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, size/m

#50 Create LICENSE
  LICENSE
Labels: documentation, size/l

#52 Create CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: documentation, size/s

#53 Fix typo
  CONTRIBUTING.md
  README.md
Labels: documentation

#55 Update README.md
  README.md
Labels: documentation, size/s
