Repository sparcs-kaist/otlplus-app, pull requests merged in 2022-09, with the labels that each got.

#61 Add my timetable in timetable page
  lib/pages/lecture_detail_page.dart
  lib/pages/main_page.dart
  lib/pages/timetable_page.dart
  lib/providers/timetable_model.dart
  lib/widgets/lecture_search.dart
  lib/widgets/timetable_tabs.dart
  pubspec.yaml
Labels: enhancement, size/s

#64 Update flutter version to 3.0.5
  .github/workflows/build.yml
  .github/workflows/coverage.yml
  .github/workflows/deploy.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  CONTRIBUTING.md
  lib/pages/timetable_page.dart
  lib/widgets/today_timetable.dart
  pubspec.lock
Labels: cicd, size/s

#65 Fix android integration test, add self-hosted runner, fix Firebase Crashlytics
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  .github/workflows/test.yml
  README.md
  android/build.gradle
  android/ci.jks
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  lib/main.dart
  lib/pages/settings_page.dart
  pubspec.lock
  pubspec.yaml
Labels: test, size/m

#66 Add english locales
  .github/workflows/test.yml
  CONTRIBUTING.md
  android/app/build.gradle
  android/gradle.properties
  assets/translations/en.json
  assets/translations/ko.json
  ios/Runner.xcodeproj/project.pbxproj
  lib/home.dart
  lib/pages/main_page.dart
  lib/pages/settings_page.dart
  lib/pages/timetable_page.dart
  pubspec.lock
  pubspec.yaml
Labels: bug, size/m, g11n
