Repository sparcs-kaist/otlplus-app, pull requests merged in 2023-07, with the labels that each got.

#92 Change iOS bundle ID, add Pods cache on GitHub Actions
  .github/workflows/build.yml
  .github/workflows/test.yml
  android/Gemfile.lock
  android/build.gradle
  ios/Gemfile.lock
  ios/OTLPlusIntents/OTLPlusIntents.entitlements
  ios/OTLWidgetsExtension.entitlements
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Runner.entitlements
  ios/fastlane/Appfile
  ios/fastlane/Fastfile
Labels: size/m, chore

#91 Add logout feature
  lib/dio_provider.dart
  lib/pages/user_page.dart
  lib/providers/auth_model.dart
  lib/providers/info_model.dart
Labels: feat, size/s

#93 Add "로그인하러 가기" button when there's no existing data in iOS Widgets
  ios/OTLPlusIntents/IntentHandler.swift
  ios/OTLWidgets/Assets.xcassets/lock.imageset/Contents.json
  ios/OTLWidgets/Assets.xcassets/lock.imageset/image 1.png
  ios/OTLWidgets/Assets.xcassets/lock.imageset/image 2.png
  ios/OTLWidgets/Assets.xcassets/lock.imageset/image.png
  ios/OTLWidgets/NextClassWidget.swift
  ios/OTLWidgets/TodayClassesWidget.swift
  ios/OTLWidgets/WeekClassesWidget.swift
  ios/Runner.xcodeproj/project.pbxproj
  lib/providers/timetable_model.dart
Labels: feat, size/m, design

#101 Resolve #37, redesign search page for timetable and dictionary page
  assets/fonts/Icons.ttf
  ios/Podfile.lock
  lib/constants/color.dart
  lib/constants/icon.dart
  lib/home.dart
  lib/main.dart
  lib/models/filter.dart
  lib/pages/course_search_page.dart
  lib/pages/dictionary_page.dart
  lib/pages/lecture_search_page.dart
  lib/pages/timetable_page.dart
  lib/providers/course_search_model.dart
  lib/providers/lecture_search_model.dart
  lib/providers/search_model.dart
  lib/widgets/base_layout.dart
  lib/widgets/course_block.dart
  lib/widgets/course_search.dart
  lib/widgets/lecture_group_block.dart
  lib/widgets/lecture_group_block_row.dart
  lib/widgets/lecture_search.dart
  lib/widgets/search_filter_panel.dart
  lib/widgets/search_textfield.dart
  lib/widgets/timetable_tabs.dart
  pubspec.yaml
  test/pages/pump_test.dart
  test/widgets/pump_test.dart
Labels: feat, size/xl

#105 Fix invalid Siri support warning message
  ios/OTLWidgets/Configuration.intentdefinition
Labels: bug, size/s

#107 Remove unused dependencies, update to JDK 17, AGP 8, fix test
  .github/workflows/build.yml
  .github/workflows/coverage.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  README.md
  android/app/build.gradle
  android/app/src/debug/AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
  android/app/src/profile/AndroidManifest.xml
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.properties
  lib/providers/info_model.dart
  lib/providers/settings_model.dart
  lib/providers/timetable_model.dart
  lib/widgets/search_filter.dart
  pubspec.lock
  pubspec.yaml
  test/pages/pump_test.dart
  test/utils/extensions.dart
  test/widgets/pump_test.dart
Labels: test, size/m, chore

#85 Resolve #67, add exam timetable and map
  assets/icons/icon-512-foreground.png
  assets/icons/icon-512.png
  assets/icons/map_pin.svg
  assets/images/bg.4556cdee.jpg
  assets/images/kaist_map.png
  assets/images/logo.png
  assets/translations/en.json
  assets/translations/ko.json
  lib/constants/color.dart
  lib/constants/text_styles.dart
  lib/constants/url.dart
  lib/extensions/semester.dart
  lib/home.dart
  lib/main.dart
  lib/pages/course_search_page.dart
  lib/pages/dictionary_page.dart
  lib/pages/lecture_detail_page.dart
  lib/pages/lecture_search_page.dart
  lib/pages/main_page.dart
  lib/pages/people_page.dart
  lib/pages/review_page.dart
  lib/pages/settings_page.dart
  lib/pages/timetable_page.dart
  lib/pages/user_page.dart
  lib/providers/course_search_model.dart
  lib/providers/lecture_search_model.dart
  lib/providers/timetable_model.dart
  lib/utils/build_app_bar.dart
  lib/widgets/base_layout.dart
  lib/widgets/course_block.dart
  lib/widgets/lecture_group_block.dart
  lib/widgets/lecture_group_block_row.dart
  lib/widgets/lecture_group_simple_block.dart
  lib/widgets/lecture_search.dart
  lib/widgets/lecture_simple_block.dart
  lib/widgets/map_view.dart
  lib/widgets/mode_control.dart
  lib/widgets/pop_up.dart
  lib/widgets/review_block.dart
  lib/widgets/review_write_block.dart
  lib/widgets/search_filter_panel.dart
  lib/widgets/search_textfield.dart
  lib/widgets/semester_picker.dart
  lib/widgets/timetable.dart
  lib/widgets/timetable_block.dart
  lib/widgets/timetable_summary.dart
  lib/widgets/timetable_tabs.dart
  lib/widgets/today_timetable.dart
  pubspec.lock
  pubspec.yaml
  test/widgets/pump_test.dart
Labels: feat, size/xl, design

#108 Resolve #96, #102, #109, 영어 번역 (시간표 제외), 전체 디자인 점검 (시간표 제외), 팝업 구현
  assets/app-event-image-en.png
  assets/app-event-image.png
  assets/fonts/Icons.ttf
  assets/icons/add.svg
  assets/icons/back.svg
  assets/icons/gear.svg
  assets/icons/info.svg
  assets/icons/person.svg
  assets/icons/search.svg
  assets/translations/en.json
  assets/translations/ko.json
  lib/constants/icon.dart
  lib/extensions/course.dart
  lib/extensions/lecture.dart
  lib/home.dart
  lib/pages/course_detail_page.dart
  lib/pages/course_search_page.dart
  lib/pages/dictionary_page.dart
  lib/pages/lecture_detail_page.dart
  lib/pages/lecture_search_page.dart
  lib/pages/liked_review_page.dart
  lib/pages/main_page.dart
  lib/pages/my_review_page.dart
  lib/pages/people_page.dart
  lib/pages/privacy_page.dart
  lib/pages/review_page.dart
  lib/pages/settings_page.dart
  lib/pages/timetable_page.dart
  lib/pages/user_page.dart
  lib/providers/course_search_model.dart
  lib/providers/info_model.dart
  lib/providers/lecture_search_model.dart
  lib/utils/build_app_bar.dart
  lib/widgets/base_layout.dart
  lib/widgets/course_block.dart
  lib/widgets/lecture_group_block.dart
  lib/widgets/lecture_group_block_row.dart
  lib/widgets/lecture_group_simple_block.dart
  lib/widgets/lecture_search.dart
  lib/widgets/lecture_simple_block.dart
  lib/widgets/pop_up.dart
  lib/widgets/review_block.dart
  lib/widgets/review_write_block.dart
  lib/widgets/search_filter_panel.dart
  lib/widgets/search_textfield.dart
  pubspec.yaml
  test/flutter_test_config.dart
  test/widgets/pump_test.dart
Labels: feat, size/xl, design
