Repository sparcs-kaist/otlplus-app, pull requests merged in 2023-09, with the labels that each got.

#145 Delete deprecated variables and modify the associated designs
  lib/constants/color.dart
  lib/pages/lecture_detail_page.dart
  lib/widgets/timetable_block.dart
  lib/widgets/today_timetable.dart
Labels: feat, size/m

#141 Resolve #139, Make iOS widget work independently
  ios/OTLPlusIntents/IntentHandler.swift
  ios/OTLWidgets/NextClassWidget.swift
  ios/OTLWidgets/OTLAPI.swift
  ios/OTLWidgets/WidgetBase.swift
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ios/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved
  lib/pages/main_page.dart
  lib/providers/timetable_model.dart
  test/widgets/pump_test.dart
Labels: bug, feat, size/l

#144 Resolve #106, Add iOS Lock Complications
  ios/OTLWidgets/LocationInlineAccessory.swift
  ios/OTLWidgets/NextClassAccessory.swift
  ios/OTLWidgets/NextClassWidget.swift
  ios/OTLWidgets/OTLWidgetBundle.swift
  ios/OTLWidgets/TimeInlineAccessory.swift
  ios/Runner.xcodeproj/project.pbxproj
Labels: feat, size/m

#146 Remove 23 fall sparcs recruiting popup
  lib/home.dart
Labels: feat, size/s

#147 Change version to 2.1.0
  pubspec.yaml
Labels: chore

#151 Change app version to 2.1.1
  pubspec.yaml
Labels: chore

#150 Fix bug that cannot export image of "내 시간표" by changing myTimetable id
  lib/providers/timetable_model.dart
Labels: bug, size/xs

#152 Resolve #134, Add language setting
  assets/translations/en.json
  assets/translations/ko.json
  lib/pages/settings_page.dart
  lib/widgets/dropdown.dart
  lib/widgets/hall_of_fame_control.dart
  lib/widgets/timetable_tabs.dart
Labels: feat, size/l, design

#136 Fix #130, Add missing iOS widgets localisations
  ios/Gemfile
  ios/Gemfile.lock
  ios/OTLPlusIntents/IntentHandler.swift
  ios/OTLWidgets/Base.lproj/Configuration.intentdefinition
  ios/OTLWidgets/Localizable.xcstrings
  ios/OTLWidgets/LocationInlineAccessory.swift
  ios/OTLWidgets/NextClassAccessory.swift
  ios/OTLWidgets/NextClassWidget.swift
  ios/OTLWidgets/OTLWidgetBundle.swift
  ios/OTLWidgets/TimeInlineAccessory.swift
  ios/OTLWidgets/TodayClassesWidget.swift
  ios/OTLWidgets/WeekClassesWidget.swift
  ios/OTLWidgets/WidgetBase.swift
  ios/OTLWidgets/en.lproj/Configuration.strings
  ios/OTLWidgets/ko.lproj/Configuration.strings
  ios/Runner.xcodeproj/project.pbxproj
Labels: bug, size/xl

#149 Resolve #148, Add supports StandBy for iOS 17
  ios/OTLWidgets/LocationInlineAccessory.swift
  ios/OTLWidgets/NextClassAccessory.swift
  ios/OTLWidgets/NextClassWidget.swift
  ios/OTLWidgets/TimeInlineAccessory.swift
  ios/OTLWidgets/WidgetBase.swift
Labels: feat, size/s

#153 Redesign Popup
  assets/icons/OTL.svg
  assets/icons/addLecture.svg
  assets/icons/alert.svg
  assets/icons/deleteLecture.svg
  assets/icons/overlap.svg
  assets/icons/timetable.svg
  assets/translations/en.json
  assets/translations/ko.json
  lib/constants/color.dart
  lib/constants/text_styles.dart
  lib/constants/url.dart
  lib/main.dart
  lib/pages/course_detail_page.dart
  lib/pages/lecture_detail_page.dart
  lib/pages/liked_review_page.dart
  lib/pages/login_page.dart
  lib/pages/main_page.dart
  lib/pages/review_page.dart
  lib/pages/settings_page.dart
  lib/pages/timetable_page.dart
  lib/pages/user_page.dart
  lib/providers/course_search_model.dart
  lib/providers/lecture_search_model.dart
  lib/providers/timetable_model.dart
  lib/utils/navigator.dart
  lib/widgets/custom_header_delegate.dart
  lib/widgets/delete_dialog.dart
  lib/widgets/expandable_text.dart
  lib/widgets/hall_of_fame_control.dart
  lib/widgets/lecture_group_block.dart
  lib/widgets/lecture_group_block_row.dart
  lib/widgets/lecture_group_simple_block.dart
  lib/widgets/otl_dialog.dart
  lib/widgets/pop_up.dart
  lib/widgets/responsive_button.dart
  lib/widgets/review_block.dart
  lib/widgets/review_mode_control.dart
  lib/widgets/search_filter_panel.dart
  lib/widgets/search_textfield.dart
  lib/widgets/timetable_mode_control.dart
  lib/widgets/timetable_tabs.dart
  pubspec.lock
  pubspec.yaml
Labels: feat, size/xl, design

#158 Resolve #157, Scrolls large widget to the top when there is no more upcoming lecture.
  ios/OTLWidgets/WeekClassesWidget.swift
  ios/OTLWidgets/WidgetBase.swift
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
Labels: feat, size/s

#159 Change to macOS 13 and Xcode 15
  .github/workflows/build.yml
  .github/workflows/test.yml
Labels: cicd, size/xs, chore

#160 Fix testing on iOS (github actions)
  .github/workflows/test.yml
Labels: size/xs, chore
