Repository sparcs-kaist/otlplus-app, pull requests merged in 2023-08, with the labels that each got.

#112 Resolve #103, #110, #114. implement review app bar, implement like cancel, resolve bug: pixel overflow, translate, text alignment, design enhancement
  assets/translations/ko.json
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  lib/constants/text_styles.dart
  lib/home.dart
  lib/pages/course_detail_page.dart
  lib/pages/course_search_page.dart
  lib/pages/lecture_detail_page.dart
  lib/pages/lecture_search_page.dart
  lib/pages/main_page.dart
  lib/pages/review_page.dart
  lib/providers/course_search_model.dart
  lib/providers/hall_of_fame_model.dart
  lib/widgets/hall_of_fame_control.dart
  lib/widgets/lecture_group_simple_block.dart
  lib/widgets/pop_up.dart
  lib/widgets/review_block.dart
  lib/widgets/review_mode_control.dart
  lib/widgets/review_write_block.dart
  lib/widgets/search_textfield.dart
  lib/widgets/timetable_mode_control.dart
  lib/widgets/timetable_tabs.dart
  pubspec.lock
  pubspec.yaml
Labels: feat, size/l, design

#118 Fix Button Pressed Effect
  assets/translations/en.json
  assets/translations/ko.json
  ios/Podfile.lock
  lib/home.dart
  lib/pages/course_detail_page.dart
  lib/pages/course_search_page.dart
  lib/pages/lecture_detail_page.dart
  lib/pages/lecture_search_page.dart
  lib/pages/main_page.dart
  lib/pages/settings_page.dart
  lib/pages/timetable_page.dart
  lib/pages/user_page.dart
  lib/providers/course_search_model.dart
  lib/providers/lecture_search_model.dart
  lib/utils/build_app_bar.dart
  lib/utils/responsive_button.dart
  lib/widgets/course_block.dart
  lib/widgets/custom_header_delegate.dart
  lib/widgets/lecture_group_block_row.dart
  lib/widgets/lecture_group_simple_block.dart
  lib/widgets/lecture_search.dart
  lib/widgets/lecture_simple_block.dart
  lib/widgets/pop_up.dart
  lib/widgets/review_block.dart
  lib/widgets/review_write_block.dart
  lib/widgets/search_filter_panel.dart
  lib/widgets/semester_picker.dart
  lib/widgets/timetable_block.dart
  pubspec.lock
  pubspec.yaml
Labels: feat, size/xl

#119 Fix search filter page
  assets/translations/en.json
  assets/translations/ko.json
  lib/main.dart
  lib/models/filter.dart
  lib/pages/course_search_page.dart
  lib/pages/lecture_search_page.dart
  lib/pages/timetable_page.dart
  lib/providers/course_search_model.dart
  lib/providers/lecture_search_model.dart
  lib/widgets/search_filter_panel.dart
Labels: feat, size/m, design

#121 Feat@final
  assets/translations/ko.json
  lib/constants/privacy.dart
  lib/providers/course_search_model.dart
  lib/providers/lecture_search_model.dart
  lib/widgets/review_block.dart
  lib/widgets/review_write_block.dart
Labels: size/s, chore, design

#122 Change version to 2.0.0, remove landscape orientation except iPadOS
  android/app/src/main/AndroidManifest.xml
  ios/Runner/Info.plist
  pubspec.yaml
  test/widgets/review_block_test.dart
Labels: size/s, chore

#124 Change version to 2.0.1
  pubspec.yaml
Labels: size/xs, chore

#120 Fix error during building with Xcode 15 beta
  ios/Runner.xcodeproj/project.pbxproj
Labels: bug, size/xs

#132 Add release drafter labels
  .github/release-drafter.yml
Labels: chore

#133 Add label "chore" to release drafter
  .github/release-drafter.yml
Labels: size/xs, chore

#137 Change server host to otl.sparcs.org
  lib/constants/url.dart
  lib/pages/login_page.dart
  lib/widgets/pop_up.dart
Labels: bug, size/xs

#138 Add feature that deleting account temporally (only iOS)
  assets/translations/en.json
  assets/translations/ko.json
  lib/pages/login_page.dart
  lib/pages/timetable_page.dart
  lib/pages/user_page.dart
  lib/providers/info_model.dart
  lib/widgets/delete_dialog.dart
Labels: feat, size/m

#140 Change version to 2.0.2, update Android deps, fix Github Actions warnings
  .github/workflows/build.yml
  .github/workflows/coverage.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  android/app/build.gradle
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
  lib/providers/info_model.dart
  pubspec.yaml
Labels: size/s, chore

#125 Resolve warning which indicate state changed after widget disposed
  lib/home.dart
  lib/pages/course_detail_page.dart
  lib/pages/course_search_page.dart
  lib/pages/lecture_detail_page.dart
  lib/pages/lecture_search_page.dart
  lib/pages/login_page.dart
  lib/pages/main_page.dart
  lib/pages/settings_page.dart
  lib/pages/timetable_page.dart
  lib/pages/user_page.dart
  lib/utils/build_app_bar.dart
  lib/utils/responsive_button.dart
  lib/widgets/course_block.dart
  lib/widgets/lecture_group_block_row.dart
  lib/widgets/lecture_group_simple_block.dart
  lib/widgets/lecture_search.dart
  lib/widgets/lecture_simple_block.dart
  lib/widgets/pop_up.dart
  lib/widgets/responsive_button.dart
  lib/widgets/review_block.dart
  lib/widgets/review_write_block.dart
  lib/widgets/search_filter_panel.dart
  lib/widgets/semester_picker.dart
  lib/widgets/timetable_block.dart
Labels: bug, size/l

#131 Add OTLNavigator and OTLScaffold
  lib/home.dart
  lib/pages/course_detail_page.dart
  lib/pages/course_search_page.dart
  lib/pages/dictionary_page.dart
  lib/pages/lecture_detail_page.dart
  lib/pages/lecture_search_page.dart
  lib/pages/liked_review_page.dart
  lib/pages/login_page.dart
  lib/pages/main_page.dart
  lib/pages/my_review_page.dart
  lib/pages/people_page.dart
  lib/pages/privacy_page.dart
  lib/pages/review_page.dart
  lib/pages/settings_page.dart
  lib/pages/timetable_page.dart
  lib/pages/user_page.dart
  lib/utils/build_app_bar.dart
  lib/utils/build_page_route.dart
  lib/utils/get_text_height.dart
  lib/utils/navigator.dart
  lib/widgets/base_layout.dart
  lib/widgets/lecture_group_block_row.dart
  lib/widgets/lecture_group_simple_block.dart
  lib/widgets/lecture_search.dart
  lib/widgets/map_view.dart
  lib/widgets/otl_scaffold.dart
  lib/widgets/pop_up.dart
  lib/widgets/review_block.dart
  lib/widgets/search_filter_panel.dart
  lib/widgets/search_textfield.dart
  lib/widgets/semester_picker.dart
  lib/widgets/timetable_block.dart
Labels: feat, size/xl

#135 Fix lecture type classification bug for HSS Elective
  lib/constants/url.dart
  lib/dio_provider.dart
  lib/models/lecture.dart
  lib/pages/lecture_search_page.dart
  lib/pages/login_page.dart
  lib/pages/review_page.dart
  lib/pages/timetable_page.dart
  lib/providers/lecture_search_model.dart
  lib/providers/timetable_model.dart
  lib/widgets/lecture_group_block_row.dart
  lib/widgets/lecture_search.dart
  lib/widgets/semester_picker.dart
  lib/widgets/timetable_summary.dart
  pubspec.lock
  pubspec.yaml
  test/models/lecture_test.dart
  test/pages/pump_test.dart
  test/utils/extensions.dart
  test/utils/samples.dart
  test/widgets/pump_test.dart
  test/widgets/review_block_test.dart
Labels: bug, cicd, test, size/m

#128 [FATAL] Fix #123, #126, fix synchronized reviews, add translation in timetable
  assets/translations/en.json
  assets/translations/ko.json
  lib/main.dart
  lib/pages/lecture_detail_page.dart
  lib/pages/main_page.dart
  lib/pages/review_page.dart
  lib/pages/timetable_page.dart
  lib/providers/hall_of_fame_model.dart
  lib/providers/latest_reviews_model.dart
  lib/widgets/expandable_text.dart
  lib/widgets/lecture_group_block.dart
  lib/widgets/lecture_group_block_row.dart
  lib/widgets/lecture_search.dart
Labels: bug, size/m

#142 Add popup for 2023 fall recruiting
  assets/popups/23f-recruiting.png
  assets/popups/app-event-image-en.png
  assets/popups/app-event-image.png
  assets/popups/graduate-planner.png
  lib/home.dart
  lib/widgets/pop_up.dart
  pubspec.yaml
Labels: feat, size/s, design

#143 Update version to 2.0.3
  android/build.gradle
  pubspec.yaml
Labels: chore
