Repository sparcs-kaist/otlplus-app, pull requests merged in 2024-09, with the labels that each got.

#189 Change Version 2.3.0 to 2.3.1
  pubspec.yaml
Labels: size/xs

#186 Send user informations to channel talk
  lib/providers/info_model.dart
Labels: feat, size/s

#191 Migrate to Kotlin DSL (Android build script)
  android/app/build.gradle
  android/app/build.gradle.kts
  android/build.gradle
  android/build.gradle.kts
  android/settings.gradle
  android/settings.gradle.kts
Labels: chore

#190 Resolve #187, implement buttonOptions
  assets/translations/en.json
  assets/translations/ko.json
  ios/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ios/Runner/AppDelegate.swift
  lib/main.dart
  lib/pages/settings_page.dart
  lib/providers/settings_model.dart
  package-lock.json
  pubspec.lock
  pubspec.yaml
Labels: bug, feat, size/s

#198 Fix build on Xcode 16, update GitHub Actions scripts
  .github/workflows/build.yml
  .github/workflows/coverage.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  android/app/build.gradle.kts
  android/build.gradle.kts
  android/gradle/wrapper/gradle-wrapper.properties
  android/settings.gradle.kts
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ios/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved
  lib/widgets/lecture_search.dart
Labels: size/m, chore

#193 Fix #184, fix modal with deleting timetable
  lib/pages/timetable_page.dart
Labels: bug, size/s

#197 Resolve #192, show more info in timetable block
  lib/widgets/timetable_block.dart
Labels: feat, size/xs, design
