Repository sparcs-kaist/otlplus-app, pull requests merged in 2024-03, with the labels that each got.

#168 Resolve #167, Edit README.md
  README.md
Labels: size/xs, chore

#171 Change iOS minimum 12
  android/Gemfile.lock
  android/app/build.gradle
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
  android/settings.gradle
  ios/Flutter/AppFrameworkInfo.plist
  ios/Gemfile.lock
  ios/Podfile
Labels: size/m, chore

#170 Resolve #169, Alert dialog when deleting last time table
  assets/translations/en.json
  assets/translations/ko.json
  lib/pages/timetable_page.dart
  lib/widgets/otl_dialog.dart
  lib/widgets/timetable_tabs.dart
  test/widgets/pump_test.dart
Labels: feat, test, size/s, g11n

#173 Resolve #172, Refactoring people page
  assets/fonts/NanumSquareB.otf
  assets/fonts/NanumSquareEB.otf
  assets/fonts/NanumSquareL.otf
  assets/fonts/NanumSquareR.otf
  assets/fonts/Raleway-Black.ttf
  assets/fonts/Raleway-Bold.ttf
  assets/fonts/Raleway-ExtraBold.ttf
  assets/fonts/Raleway-Light.ttf
  assets/fonts/Raleway-Medium.ttf
  assets/fonts/Raleway-Regular.ttf
  assets/fonts/Raleway-Thin.ttf
  assets/icons/SPARCS.svg
  lib/pages/people_page.dart
  pubspec.yaml
Labels: feat, size/m, refactor

#174 Add SingleChildScrollView in People Page
  lib/pages/people_page.dart
Labels: bug, size/s
