Repository sparcs-kaist/otlplus-app, pull requests merged in 2024-10, with the labels that each got.

#201 Bump up version to 2.4.0
  .fvmrc
  .github/workflows/build.yml
  .github/workflows/coverage.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  .gitignore
  android/Gemfile.lock
  android/gradle/wrapper/gradle-wrapper.properties
  android/settings.gradle.kts
  ios/Gemfile.lock
  pubspec.lock
  pubspec.yaml
  test/models/lecture_test.dart
Labels: test, size/m, chore

#200 Resolve #199, Fix iOS widget not working and add support tinted widget
  ios/OTLWidgets/NextClassWidget.swift
  ios/OTLWidgets/OTLAPI.swift
  ios/OTLWidgets/OTLWidgetBundle.swift
  ios/OTLWidgets/TodayClassesWidget.swift
  ios/OTLWidgets/WeekClassesWidget.swift
  lib/pages/main_page.dart
  pubspec.lock
Labels: bug, feat, size/l, chore

#205 Update fastlane version
  android/Gemfile.lock
  android/settings.gradle.kts
  ios/Gemfile.lock
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
Labels: size/m, chore
